# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        shop_user:
            entity:
                class: ShopBundle:User
                property: username

    encoders:
            ShopBundle\Entity\User:
                algorithm: bcrypt
                cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: shop_user # Défini plus haut
            anonymous: ~
            # http_basic: ~

            # Active la prise en charge de notre formulaire de login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: shop_login
                check_path: shop_login

            # Active le logout (ne fonctionne pas avec http_basic)
            logout:
                path:   /logout
                target: shop_login

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
