parameters:
    image_directory: '%kernel.root_dir%/../var/data/image'


services:
    shop.upload.image_uploader:
        class: ShopBundle\Service\Upload\Uploader
        arguments: ['%image_directory%']

    shop.event_listener.image:
        class: ShopBundle\EventListener\ImageEventListener
        arguments: ['@shop.upload.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    shop.twig.shop_extension:
        class: ShopBundle\Service\Twig\ShopExtension
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    shop.repository.product:
        class: ShopBundle\Repository\ProductRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - ShopBundle\Entity\Product

    shop.service.cart_provider:
        class: ShopBundle\Service\Cart\CartProvider
        arguments:
            - '@session'
            - '@shop.repository.product'

    shop.service.cart_calculator:
        class: ShopBundle\Service\Cart\CartCalculator
        arguments:
            - '@shop.service.cart_provider'

    shop.service.user_manager:
        class: ShopBundle\Service\User\UserManager
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'
            - '@security.password_encoder'
