shop_admin_feature_index:
    path:     /
    defaults: { _controller: "ShopBundle:Admin/Feature:index" }
    methods:  GET

shop_admin_feature_show:
    path:     /{id}/show
    defaults: { _controller: "ShopBundle:Admin/Feature:show" }
    methods:  GET

shop_admin_feature_new:
    path:     /new
    defaults: { _controller: "ShopBundle:Admin/Feature:new" }
    methods:  [GET, POST]

shop_admin_feature_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShopBundle:Admin/Feature:edit" }
    methods:  [GET, POST]

shop_admin_feature_delete:
    path:     /{id}/delete
    defaults: { _controller: "ShopBundle:Admin/Feature:delete" }
    methods:  DELETE
